# GitHub Actions for CI on the main branch and pull-requests.
#    This runs lint checkers on Linux, testing and code coverage on all platforms,
#    It also runs as scheduled on Sunday mornings just in case.

name: CI

on:
  push:
    branches:
      - "main"
  pull_request:
    branches:
      - "main"
  # schedule:
    # Run by default Sunday morning at 3:30:
    #   Scheduled workflows run on the latest commit on the default or base branch.
    #   (from https://help.github.com/en/actions/reference/events-that-trigger-workflows#scheduled-events-schedule)
    # - cron: "30 3 * * 0"

jobs:
  lint:
    name: Lint ubuntu-latest Py3.12
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Additional info about the build
      shell: bash
      run: |
        uname -a
        df -h
        ulimit -a
    # More info on options: https://github.com/conda-incubator/setup-miniconda
    - uses: conda-incubator/setup-miniconda@v3
      with:
        python-version: 3.12
        environment-file: devtools/conda-envs/ci.yaml
        activate-environment: ci
        auto-update-conda: false
        auto-activate-base: false
        show-channel-urls: true
    - name: Install package
      # conda setup requires this special shell
      shell: bash -l {0}
      run: |
        python -m pip install . --no-deps
        conda list
    - name: Run linters
      shell: bash -l {0}
      run: |
        black --check --diff seamm_installer tests
        flake8 seamm_installer tests

  test:
    name: Test ${{ matrix.os }} Py${{ matrix.python-version }}
    runs-on: ${{ matrix.os }}
    needs: lint
    strategy:
      matrix:
        os: [macOS-latest, ubuntu-latest]
        python-version: [3.11, 3.12]
    steps:
    - uses: actions/checkout@v4
    - name: Additional info about the build
      shell: bash
      run: |
        uname -a
        df -h
        ulimit -a
    - uses: conda-incubator/setup-miniconda@v3
      with:
        python-version: ${{ matrix.python-version }}
        environment-file: devtools/conda-envs/ci.yaml
        activate-environment: ci
        auto-update-conda: false
        auto-activate-base: false
        show-channel-urls: true
    - name: Install package
      shell: bash -l {0}
      run: |
        python -m pip install . --no-deps
        conda list
    - name: Run tests
      shell: bash -l {0}
      run: |
        pytest -v --cov=seamm_installer --cov-report=xml --color=yes tests/
    - name: CodeCov
      uses: codecov/codecov-action@v2
      with:
        file: ./coverage.xml
        flags: unittests
        name: codecov-${{ matrix.os }}-py${{ matrix.python-version }}
